### PR TITLE
Use `files` property in package.json

### PR DESCRIPTION
**Pull request by kevva**

### CODE REVIEW

**Comment by rvagg** [comment]
I'm pretty -1 on this for similar reasons stated by others in iojs/readable-stream#100. I'm fine with minimising release size but I'm also very wary of using .npmignore and try to avoid it because it _overrides_ .gitignore so you need to keep them in sync and constantly be aware of what it's doing (it's a blind-spot).

What is the package size difference you're looking at for this and can you explain how this is causing _real_ problems for you (not just theoretical ones).

**Comment by sindresorhus** [comment]
through2 is used by a LOT of projects and until npm dedupes by default this would help some KBs.

**Comment by rmg** [comment]
@rvagg this PR looks like it is removing the existing .npmignore file, so that part seems like a good idea.

**Comment by stevemao** [comment]
ref: https://github.com/nodejs/readable-stream/pull/100

**Comment by arthurvr** [comment]
:+1:

**Pull request closed without merging**
