### PR TITLE
Update to latest shiny stuff

### PR DESCRIPTION
**Pull request by rvagg**
Nothing revolutionary

* readable-stream@3
* remove sauce test garbage
* new tape & bl for testing
* no Buffer constructor in test
* travis update (is it connected?)
* remove license year

### CODE REVIEW

**Comment by n2liquid** [comment]
Are you sure copyright years are optional in copyright notices?

**Comment by rvagg** [comment]
yeah, sure enough that I'm just going to do it

**Comment by SneakyFish5** [comment]
Is it possible to update to 3.0.2? Was going to open a PR to do so to fix an NPM bug seen [here](https://github.com/npm/cli/pull/59) but if you are already updating this may save me some work!

**Comment by wmhilton** [comment]
Can we make it depend on _either_ 2 or 3? E.g.
```diff
-  "readable-stream": "^3.0.1",
+  "readable-stream": "2 || 3",
```

I use `through2` in client side code and I'm trying very hard not to end up with multiple versions of `readable-stream` in the Webpack bundle.

**Comment by dwieeb** [comment]
@rvagg Need help with anything? I'd love to see this merged. If a prerelease is made for this, I can help test.

**Comment by jimmywarting** [comment]
While we are at it, can we replace xtend for Object.assign?

**Comment by wmhilton** [comment]
Is there anything blocking this PR from being merged? I'm in the opposite situation now than I was in September... all my other dependencies have been updated to use `readable-stream@3.x` and now `through2` is increasing my Webpack bundle size by pulling in an old version of `readable-stream`. 😆

**Comment by rvagg** [comment]
If you want `Object.assign()` then I welcome a separate pull request for discussion @jimmywarting. I don't recall where it was but I ended up rejecting that in another project (I don't think it was here?) for perf reasons I think. I don't know if that's out of date now with Node 10 but some simple benchmarks might be needed too.

Included `nyc` in this latest version for `npm test` and also switched from `require('readable-stream/transform')` to `require('readable-stream').Transform` which is apparently best practice now (I missed that boat!)

This is a semver-patch bump, I can't find a reason for it to be semver-minor, crossing fingers that I'm not overlooking anything that might break anyone's stuff in prod. Really the only change to `through2.js` is the `require()` change so I don't see why it would break.

`v2.0.4` is now in npm. Thanks for your patience all!

**Comment by dwieeb** [comment]
Is Node 6 now a requirement? If so, that's one reason it should be 3.0.0. (Haven't tested this.) I know split2 went to 3.0.0 for `readable-streams@3`: https://github.com/mcollina/split2/pull/19

**Comment by wmhilton** [comment]
@dwieeb I don't think Node 6 is a strict requirement, because in the package.json he lists `"readable-stream": "2 || 3"`. But I suppose maybe perhaps that applications running on Node < 6 not using a lockfile for installations might break?

**Comment by dwieeb** [comment]
@wmhilton But this module is now using `let/const` so Node 0.11 won't work anymore. It doesn't matter to me personally, and I don't think anyone will ever complain, I'm just pointing it out.

**Comment by rvagg** [comment]
Note: as per #95, I've rolled this back and went with a readable-stream@2 pin for 2.0.5 and am maintaining the diff in a `v2.x` branch. 3.0.0 has been published and has the `2||3` dependency so you could do pinning yourself if you wanted. So yeah, Node 0.10 to 4 should use 2.x.

**Comment by wmhilton** [comment]
> I suppose maybe perhaps that applications running on Node < 6 not using a lockfile for installations might break?

And suddenly all the people using node 0.10 and npm 1.x came out of the woodwork. That's seriously scary LoL.

**Pull request closed without merging**
