### PR TITLE
Fix incorrect fallback pattern for readable-stream

### PR DESCRIPTION
**Pull request by heri16**

### CODE REVIEW

**Comment by mafintosh** [comment]
We don't use readable-stream as a fallback but as a way to ensure which version of streams we get.

**Comment by heri16** [comment]
The proper way to require readable stream is require(‘readable-stream’).Transform .

This needs fixing

**Comment by mafintosh** [comment]
I'm not sure I follow :)

``` js
require('readable-stream/transform') === require('readable-stream').Transform
```

Also `require('readable-stream').Transform` is never not available for the semver range we track?

**Comment by heri16** [comment]
Will delete this branch and submit another PR once I get to my laptop.

**Comment by mafintosh** [comment]
Ah. Yea I have no problem using the .Transform import instead so feel free to PR that

**Pull request closed without merging**
